name: Southindies - Recepies from the south
markdown: kramdown
highlighter: rouge
permalink: date
google_analytics_code: UA-89617148-1
url: http://southindies.in
exclude:
- config.ru
- Gemfile
- Gemfile.lock
- Rakefile
- README.markdown
- bin
- public
- vendor
